version: '2'
services:
  ui:
    image: devopsbyexample/contacts-ui
    ports:
      - "8080:80"
    depends_on:
      - api
  api:
    image: devopsbyexample/contacts-api
    environment:
      - DB_HOST=db
      - DB_NAME=contacts
      - DB_USER=test
      - DB_PASSWORD=test
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=contacts
